import { chromium } from 'playwright-core'

const BASE = 'http://localhost:4173/Vision-board-/'
const CHROME = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome'
let failures = 0
const ok = (name, cond, extra = '') => {
  if (cond) console.log(`  ✓ ${name}`)
  else { failures++; console.log(`  ✗ FAIL: ${name} ${extra}`) }
}

const browser = await chromium.launch({ executablePath: CHROME, args: ['--no-sandbox'] })
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 } })
const page = await ctx.newPage()
const consoleErrors = []
page.on('console', m => { if (m.type() === 'error') consoleErrors.push(m.text()) })
page.on('pageerror', e => consoleErrors.push(String(e)))

const today = new Date()
const iso = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`
const store = () => page.evaluate(() => JSON.parse(localStorage.getItem('matt-os-state-v1')))

console.log('1. Today screen')
await page.goto(BASE, { waitUntil: 'networkidle' })
ok('brand visible', await page.getByText('MATT OS').first().isVisible())
let body = await page.textContent('body')
ok('day type shown', /WORK DAY|OFF DAY/.test(body))
ok('capacity shown', /CAPACITY/i.test(body))
ok('anchors card', /ANCHORS/i.test(body))
ok('network balance card', /NETWORK BALANCE/i.test(body))
ok('life radar', body.includes('Life Radar'))

console.log('2. Anchors tap + streak persistence')
const firstAnchor = page.locator('.anchor-row').first()
const anchorName = (await firstAnchor.textContent()).trim()
await firstAnchor.click()
await page.waitForTimeout(200)
ok('anchor marked done', await page.locator('.anchor-box.on').count() >= 1, anchorName)
let s = await store()
ok('anchor persisted to log', Object.keys(s.commitmentLog[iso] ?? {}).length >= 1)
// twice-daily anchor should go 1/2 then done
const teeth = page.locator('.anchor-row', { hasText: 'Teeth' }).first()
await teeth.click()
await page.waitForTimeout(150)
ok('twice-daily shows partial', (await teeth.textContent()).includes('1/2'))
await teeth.click()
await page.waitForTimeout(150)
ok('twice-daily completes', await teeth.locator('.anchor-box.on').count() === 1)

console.log('2b. Window + assignment')
ok('window strip', await page.locator('.window-strip').count() === 1)
ok('window day 1', (await page.textContent('.window-strip')).includes('DAY 1'))
ok('assignment hero', await page.locator('.assign').count() === 1)
ok('assignment names a channel', (await page.textContent('.assign-channel')).trim().length > 2)
ok('assignment has rooms', await page.locator('.assign-list li').count() >= 1)
ok('assignment explains why', (await page.textContent('.assign-why')).length > 20)
{
  const first = await page.locator('.assign-list li button').first().textContent()
  await page.locator('.assign-list li button').first().click()
  await page.waitForTimeout(250)
  ok('assignment room opens', (await page.textContent('main')).includes('ENTER THIS ROOM') ||
     (await page.textContent('main')).includes('LOG ANOTHER SESSION'), first)
  await page.locator('.nav button', { hasText: 'Today' }).click()
  await page.waitForTimeout(200)
}

console.log('2c. Network of channels')
await page.locator('.nav button', { hasText: 'Network' }).click()
await page.waitForTimeout(250)
ok('8 channels render', await page.locator('.channel-card').count() === 8,
   String(await page.locator('.channel-card').count()))
{
  const t = await page.textContent('main')
  ok('TRUCE channel exists', t.includes('TRUCE'))
  ok('balance note shown', t.includes('starve') || t.includes('running dry') || t.includes('balanced'))
}
await page.locator('.channel-card', { hasText: 'TRUCE' }).click()
await page.waitForTimeout(250)
ok('channel screen opens', (await page.textContent('main')).includes('The channel'))
ok('channel shows rooms', (await page.textContent('main')).includes('Editing'))
await page.locator('main .chip', { hasText: '5' }).first().click()
await page.waitForTimeout(200)
{
  const st = await store()
  ok('channel weight editable', st.channels.find(c => c.id === 'ch-truce').weight === 5)
}
await page.locator('.nav button', { hasText: 'Today' }).click()
await page.waitForTimeout(200)

console.log('2d. Window screen')
await page.evaluate(() => { window.location.hash = '/window' })
await page.waitForTimeout(300)
{
  const t = await page.textContent('main')
  ok('window screen', t.includes('Window 02'))
  ok('window ring', await page.locator('.window-ring').count() === 1)
  ok('channel equity', t.includes('Channel equity'))
}

console.log('3. Rooms list + filters')
await page.evaluate(() => { window.location.hash = '/rooms' })
await page.waitForTimeout(300)
await page.waitForTimeout(200)
ok('room cards render', await page.locator('.room-card').count() >= 3)
await page.locator('main .chip', { hasText: 'All' }).click()
await page.waitForTimeout(200)
const allCount = await page.locator('.room-card').count()
ok('all rooms listed', allCount >= 20, `got ${allCount}`)
await page.locator('main .chip', { hasText: 'Maintenance' }).click()
await page.waitForTimeout(200)
ok('accora in maintenance', (await page.textContent('main')).includes('Accora Brain'))

console.log('4. Enter a room and log a session')
await page.locator('main .chip', { hasText: 'All' }).click()
await page.waitForTimeout(200)
ok('plants room exists', (await page.textContent('main')).includes('Plants'))
await page.locator('.room-card', { hasText: 'French' }).first().click()
await page.waitForTimeout(250)
ok('room screen opened', (await page.textContent('main')).includes('Duolingo daily'))
ok('intention shown', await page.locator('.room-intention').count() === 1)
await page.getByRole('button', { name: /ENTER THIS ROOM|LOG ANOTHER SESSION/ }).click()
await page.waitForSelector('.sheet')
await page.locator('.sheet .stepper button[aria-label="increase"]').click()
await page.locator('#s-note').fill('Duolingo + podcast on the bus')
await page.getByRole('switch', { name: 'Filmed it' }).click()
await page.getByRole('button', { name: 'Log session' }).click()
await page.waitForTimeout(300)
s = await store()
const sess = s.roomSessions.find(x => x.roomId === 'r-french')
ok('session saved', !!sess && sess.minutes === 25, JSON.stringify(sess))
ok('filmed flag saved', sess?.filmed === true)
ok('filming created footage', s.content.some(c => c.roomId === 'r-french' && c.kind === 'footage'))
ok('room lastEntered set', s.rooms.find(r => r.id === 'r-french')?.lastEntered === iso)

console.log('5. Room capture')
await page.locator('main input[placeholder^="New idea"]').fill('Try shadowing French podcasts')
await page.getByRole('button', { name: 'Add', exact: true }).click()
await page.waitForTimeout(250)
s = await store()
ok('capture saved', s.roomCaptures.some(c => c.roomId === 'r-french'))

console.log('6. Capture tab + edit session consumes footage')
await page.locator('.nav button', { hasText: 'Capture' }).click()
await page.waitForTimeout(200)
ok('edit queue shows unedited', (await page.textContent('main')).includes('unedited'))
await page.locator('main input').first().fill('Walked the property at golden hour')
await page.getByRole('button', { name: 'Add', exact: true }).click()
await page.waitForTimeout(250)
await page.getByRole('button', { name: 'Start an edit session' }).click()
await page.waitForSelector('.sheet')
await page.getByRole('button', { name: 'Log edit session' }).click()
await page.waitForTimeout(300)
s = await store()
ok('edit session saved', s.edits.length === 1, JSON.stringify(s.edits))
ok('footage marked edited', s.content.filter(c => c.editId).length >= 2)
ok('editing room got a session', s.roomSessions.some(x => x.roomId === 'r-editing'))

console.log('7. Monk mode')
await page.locator('.nav button', { hasText: 'Life' }).click()
await page.locator('main .row', { hasText: 'Monk' }).first().click()
await page.waitForTimeout(200)
ok('monk setup shown', (await page.textContent('main')).includes('60 days, no vices'))
await page.locator('main .chip', { hasText: 'Weed' }).click()
await page.getByRole('button', { name: 'START DAY 1' }).click()
await page.waitForTimeout(250)
ok('challenge started', (await page.textContent('main')).includes('Day 1 of 60'))
await page.getByRole('button', { name: 'Clean', exact: true }).click()
await page.waitForTimeout(250)
s = await store()
ok('clean day logged', s.challengeLog[iso] === true)
ok('challenge active', s.challenge.active === true && s.challenge.startDate === iso)
await page.locator('.nav button', { hasText: 'Today' }).click()
await page.waitForTimeout(200)
ok('monk card on Today', await page.locator('.monk-card').count() === 1)

console.log('8. Collections pipeline')
await page.locator('.nav button', { hasText: 'Life' }).click()
await page.locator('main .row', { hasText: 'Collections' }).first().click()
await page.waitForTimeout(200)
await page.getByRole('button', { name: /Add to Art & Frames/ }).click()
await page.waitForSelector('.sheet')
await page.locator('#ci-title').fill('Basquiat print')
await page.locator('#ci-maker').fill('Jean-Michel Basquiat')
await page.getByRole('button', { name: 'Add', exact: true }).click()
await page.waitForTimeout(250)
ok('item added to want', (await page.textContent('main')).includes('Basquiat print'))
await page.getByRole('button', { name: '→ Have' }).click()
await page.waitForTimeout(250)
s = await store()
ok('advanced to acquired', s.collection[0].status === 'acquired')
await page.getByRole('button', { name: '→ Framed' }).click()
await page.waitForTimeout(250)
s = await store()
ok('advanced to framed', s.collection[0].status === 'framed')

console.log('9. Wishlist restraint')
await page.locator('.nav button', { hasText: 'Life' }).click()
await page.locator('main .row', { hasText: 'Want list' }).first().click()
await page.waitForTimeout(200)
body = await page.textContent('main')
ok('camera seeded', body.includes('Camera') && body.includes('600'))
ok('minimal spend toggle', body.includes('Minimal spending month'))

console.log('10. Check-in with meals + pushups, persists over reload')
await page.locator('.nav button', { hasText: 'Today' }).click()
await page.getByRole('button', { name: '60-second check-in' }).click()
await page.waitForTimeout(250)
await page.locator('main .chip', { hasText: 'Lunch' }).click()
await page.locator('main .chip', { hasText: 'Dinner' }).click()
await page.locator('#energy').fill('6')
const pushStepper = page.locator('.stepper').nth(1)
await pushStepper.getByRole('button', { name: 'increase' }).click()
await page.waitForTimeout(700)
await page.reload({ waitUntil: 'networkidle' })
await page.waitForTimeout(300)
s = await store()
const c = s.checkins[iso]
ok('lunch saved', c?.lunch === true)
ok('dinner saved', c?.dinner === true)
ok('energy saved', c?.energy === 6, `got ${c?.energy}`)
ok('pushups saved', c?.pushups === 10, `got ${c?.pushups}`)
ok('anchors survived reload', Object.keys(s.commitmentLog[iso] ?? {}).length >= 1)
ok('monk survived reload', s.challenge.active === true)

console.log('11. Weekly reset shapes the day')
await page.locator('.nav button', { hasText: 'Week' }).click()
await page.waitForTimeout(250)
body = await page.textContent('main')
ok('dump stats render', body.includes('rooms entered') && body.includes('hours invested'))
for (const d of ['French', 'Creative', 'Body']) {
  await page.locator('main .chip', { hasText: new RegExp(`^${d}$`) }).first().click()
}
await page.getByRole('button', { name: /Set weekly priorities|Update weekly priorities/ }).click()
await page.waitForTimeout(250)
ok('review saved', (await page.textContent('main')).includes('Saved'))
await page.locator('.nav button', { hasText: 'Today' }).click()
await page.waitForTimeout(250)
ok('today reflects priorities', (await page.textContent('main')).includes("this week's priorities"))

console.log('12. WHAT SHOULD I DO engine')
await page.getByRole('button', { name: 'WHAT SHOULD I DO?' }).click()
await page.waitForSelector('.sheet')
const rec = await page.textContent('.sheet')
ok('recommendation has context', /It's/.test(rec))
ok('recommendation has steps', await page.locator('.sheet .plist li').count() >= 2)
await page.getByRole('button', { name: 'Got it' }).click()

console.log('13. Schedule change moves capacity')
const capBefore = (await page.textContent('.capacity-num')).trim()
await page.locator('.nav button', { hasText: 'Life' }).click()
await page.locator('main .row', { hasText: 'Settings' }).first().click()
await page.waitForTimeout(200)
const dayName = today.toLocaleDateString('en-US', { weekday: 'long' })
await page.getByRole('switch', { name: `${dayName} work day` }).click()
await page.locator('.nav button', { hasText: 'Today' }).click()
await page.waitForTimeout(250)
ok('capacity changed', (await page.textContent('.capacity-num')).trim() !== capBefore,
  `${capBefore} -> ${(await page.textContent('.capacity-num')).trim()}`)

console.log('14. All subscreens reachable')
await page.locator('.nav button', { hasText: 'Life' }).click()
for (const sub of ['Body', 'Career', 'French', 'Money', 'Mind', 'Routines', 'Settings']) {
  await page.locator('main .row', { hasText: sub }).first().click()
  await page.waitForTimeout(180)
  ok(`subscreen ${sub}`, (await page.textContent('main')).length > 80)
  await page.getByRole('button', { name: '← Life' }).click()
  await page.waitForTimeout(150)
}

console.log('15. PWA config')
const manifest = await page.evaluate(async () => (await fetch('/Vision-board-/manifest.webmanifest')).json())
ok('manifest name', manifest.name === 'Matt OS')
ok('manifest scoped to subpath', manifest.start_url === '/Vision-board-/')
ok('service worker served', await page.evaluate(async () => (await fetch('/Vision-board-/sw.js')).status) === 200)
ok('apple touch icon', await page.evaluate(async () => (await fetch('/Vision-board-/apple-touch-icon.png')).status) === 200)

console.log('16. Desktop + no console errors')
await page.setViewportSize({ width: 1280, height: 800 })
await page.locator('.nav button', { hasText: 'Today' }).click()
await page.waitForTimeout(200)
ok('desktop renders', await page.getByText('MATT OS').first().isVisible())
const realErrors = consoleErrors.filter(e => !e.includes('favicon'))
ok('no console errors', realErrors.length === 0, JSON.stringify(realErrors.slice(0, 3)))

await browser.close()
console.log(failures === 0 ? '\nALL CHECKS PASSED' : `\n${failures} FAILURES`)
process.exit(failures === 0 ? 0 : 1)
